services:
  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  server:
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    restart: unless-stopped
    environment:
      - NODE_ENV=prod
      - PORT=3003
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      db:
        condition: service_healthy

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - '8081:8080'

volumes:
  postgres-data:
