version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    container_name: android-back-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: android
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - my_network

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - db
    ports:
      - '8081:8080'
    networks:
      - my_network

networks:
  my_network:

volumes:
  db_data:
