services:
  server:
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=prod
      - PORT=3003
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres-data:
