services:
  server:
    networks:
      - livraison_my_network
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=prod
      - PORT=3003
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db-1:5432/${POSTGRES_DB}
    ports:
      - '${PORT}:${PORT}'

volumes:
  postgres-data:
networks:
    livraison_my_network:
        external: true
